networks:
  django_network:
    driver: bridge

services:
  api:
    build:
      context: .
    env_file:
      - .env.production
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: ["sh", "-c", "cd ./api python manage.py makemigrations && python manage.py migrate && python manage.py runserver 127.0.0.1:8000"]
    networks:
      - django_network
    