networks:
  django_network:
    driver: bridge

services:
  api:
    build:
      context: .
    env_file:
      - .env.production
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: "./entrypoint.sh"
    networks:
      - django_network
    