networks:
  django_network:
    driver: bridge

services:
  api:
    build:
      context: .
    env_file:
      - .env.production
    ports:
      - "8000:8000"
    restart: unless-stopped
    working_dir: /app/api
    command: "daphne -b 0.0.0.0 -p 8000 api.asgi:application"
    networks:
      - django_network
    